/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string;
  full_name: string;
  id: Generated<number>;
  is_default: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actor_role_id: number | null;
  actor_user_id: number | null;
  changes_diff: Json | null;
  created_at: Generated<Timestamp>;
  entity: string;
  entity_id: string | null;
  id: Generated<Int8>;
  payload: Json | null;
  permission_code: string | null;
}

export interface AuthPassword {
  password_hash: string;
  password_updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface AuthSession {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  revoked_at: Timestamp | null;
  role_id: number;
  token_hash: string;
  user_agent: string | null;
  user_id: number;
}

export interface Client {
  address: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  dob: Timestamp;
  email: string;
  first_name: string;
  gender_id: number;
  id: Generated<number>;
  last_name: string;
  name_parts: string[];
  ndis_number: string;
  phone_number: string | null;
  pricing_region: string;
  unit_building: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Gender {
  code: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<number>;
  label: string;
  updated_at: Generated<Timestamp>;
}

export interface Invoice {
  amount: Numeric | null;
  client_id: number | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expected_amount: Numeric | null;
  id: Generated<number>;
  invoice_date: Timestamp | null;
  invoice_number: string | null;
  provider_id: number | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface InvoiceItem {
  amount: Numeric | null;
  category_id: number | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  input_rate: Numeric | null;
  invoice_id: number;
  max_rate: Numeric | null;
  rate_set_id: number | null;
  sort_order: Generated<number>;
  start_date: Timestamp | null;
  support_item_id: number | null;
  unit: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface InvoiceUploadBatch {
  created_at: Generated<Timestamp>;
  error_message: string | null;
  file_count: number;
  id: Generated<string>;
  status: Generated<string>;
  total_size: Int8;
  updated_at: Generated<Timestamp>;
  uploaded_by: number;
}

export interface InvoiceUploadFile {
  ai_provider: string | null;
  attempt_count: Generated<number>;
  batch_id: string;
  completion_tokens: number | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  etag: string;
  extraction_result: Json | null;
  id: Generated<string>;
  invoice_id: number | null;
  model: string | null;
  object_key: string;
  original_name: string;
  processing_completed_at: Timestamp | null;
  processing_started_at: Timestamp | null;
  processing_status: Generated<string>;
  prompt_tokens: number | null;
  size: Int8;
  total_tokens: number | null;
  updated_at: Generated<Timestamp>;
  warnings: Generated<Json>;
}

export interface Provider {
  abn: string;
  address: string | null;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  id: Generated<number>;
  name: string;
  name_parts: string[];
  phone_number: string | null;
  unit_building: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RateSet {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  start_date: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface RateSetCategory {
  category_name: string;
  category_number: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  rate_set_id: number;
  sorting: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface RateSetSupportItem {
  category_id: number;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  item_name: string;
  item_number: string;
  rate_set_id: number;
  sorting: Generated<number>;
  unit: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RateSetSupportItemAttribute {
  attribute_code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  support_item_id: number;
  value: Generated<boolean>;
}

export interface RateSetSupportItemAttributeType {
  code: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  label: string;
}

export interface RateSetSupportItemPrice {
  created_at: Generated<Timestamp>;
  end_date: Timestamp | null;
  id: Generated<number>;
  pricing_region_code: string | null;
  rate_set_id: number;
  start_date: Timestamp;
  support_item_id: number;
  type_id: number | null;
  unit_price: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface RateSetSupportItemPricingRegion {
  code: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  full_label: string;
  label: string;
}

export interface RateSetSupportItemType {
  code: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<number>;
  label: string;
}

export interface RbacPermission {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  label: string;
}

export interface RbacRole {
  code: string;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<number>;
  is_default: Generated<boolean>;
  label: string;
}

export interface RbacUserRole {
  created_at: Generated<Timestamp>;
  role_id: number;
  user_id: number;
}

export interface RbacUserRolePermission {
  created_at: Generated<Timestamp>;
  permission_id: number;
  role_id: number;
}

export interface DB {
  app_user: AppUser;
  audit_log: AuditLog;
  auth_password: AuthPassword;
  auth_session: AuthSession;
  client: Client;
  gender: Gender;
  invoice: Invoice;
  invoice_item: InvoiceItem;
  invoice_upload_batch: InvoiceUploadBatch;
  invoice_upload_file: InvoiceUploadFile;
  provider: Provider;
  rate_set: RateSet;
  rate_set_category: RateSetCategory;
  rate_set_support_item: RateSetSupportItem;
  rate_set_support_item_attribute: RateSetSupportItemAttribute;
  rate_set_support_item_attribute_type: RateSetSupportItemAttributeType;
  rate_set_support_item_price: RateSetSupportItemPrice;
  rate_set_support_item_pricing_region: RateSetSupportItemPricingRegion;
  rate_set_support_item_type: RateSetSupportItemType;
  rbac_permission: RbacPermission;
  rbac_role: RbacRole;
  rbac_user_role: RbacUserRole;
  rbac_user_role_permission: RbacUserRolePermission;
}
